accounts:
- Goldfish/accounts/*
- goldfishh/controllers/accounts_controller.py
- goldfishh/controllers/taxes_and_totals.py

stock:
- goldfishh/stock/*
- goldfishh/controllers/stock_controller.py
- goldfishh/controllers/item_variant.py

assets:
- goldfishh/assets/*

regional:
- goldfishh/regional/*

selling:
- goldfishh/selling/*
- goldfishh/controllers/selling_controller.py

buying:
- goldfishh/buying/*
- goldfishh/controllers/buying_controller.py

support:
- goldfishh/support/*

POS:
- pos*

ecommerce:
- goldfishh/e_commerce/*

maintenance:
- goldfishh/maintenance/*

manufacturing:
- goldfishh/manufacturing/*

crm:
- goldfishh/crm/*

HR:
- goldfishh/hr/*

payroll:
- goldfishh/payroll*

projects:
- goldfishh/projects/*

# Any python files modifed but no test files modified
needs-tests:
- any: ['goldfishh/**/*.py']
  all: ['!goldfishh/**/test*.py']
